# 2. 넘파이로 텐서 만들기(벡터와 행렬 만들기)

In [1]:
import numpy as np

### 1) 1D with Numpy

In [2]:
# 1차원 벡터 만들기
t = np.array([0., 1., 2., 3., 4., 5., 6.])
# List를 생성해서 np.array로 1차원 array로 변환함
print(t)

[0. 1. 2. 3. 4. 5. 6.]


In [3]:
# 1차원 벡터의 차원과 크기
print('Rank of t: ', t.ndim)
print('Shape of t: ', t.shape)

Rank of t:  1
Shape of t:  (7,)


### 2) 2D with Numpy

In [4]:
# 2차원 행렬 만들기
t = np.array([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.], [10., 11., 12.]])
print(t)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]


In [5]:
# 2차원 행렬의 차원과 크기
print('Rank  of t: ', t.ndim)
print('Shape of t: ', t.shape)

Rank  of t:  2
Shape of t:  (4, 3)


# 3. 파이토치 텐서 선언하기(PyTorch Tensor Allocation)

In [6]:
import torch

### 1) 1D with PyTorch

In [7]:
# 1차원 벡터 만들기
t = torch.FloatTensor([0., 1., 2., 3., 4., 5., 6.])
print(t)

tensor([0., 1., 2., 3., 4., 5., 6.])


In [8]:
# 1차원 벡터의 차원과 크기
print(t.dim())  # rank. 즉, 차원
print(t.shape)  # shape
print(t.size()) # shape

1
torch.Size([7])
torch.Size([7])


### 2) 2D with PyTorch

In [9]:
# 2차원 행렬 만들기
t = torch.FloatTensor([[1., 2., 3.],
                       [4., 5., 6.],
                       [7., 8., 9.],
                       [10., 11., 12.]
                      ])
print(t)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])


In [10]:
# 2차원 행렬의 차원과 크기
print(t.dim())  # rank. 즉, 차원
print(t.size()) # shape

2
torch.Size([4, 3])


### 3) 브로드캐스팅(Broadcasting)
딥러닝을 하게되면 불가피하게 크기가 다른 행렬 또는 텐서에 대해서 사칙 연산을 수행할 필요가 있는 경우가 생김.  
이를 위해 PyTorch에서는 자동으로 크기를 맞춰서 연산을 수행하게 만드는 **브로드캐스팅**이라는 기능을 제공

In [11]:
# Vector + scalar
m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([3]) # [3] -> [3, 3]
print(m1 + m2)

tensor([[4., 5.]])


In [12]:
# 2 x 1 Vector + 1 x 2 Vector
m1 = torch.FloatTensor([[1, 2]]) # [1, 2] -> [[1, 2], [1, 2]]
m2 = torch.FloatTensor([[3], [4]]) # [[3],[4]] -> [[3, 3],[4, 4]]
print(m1 + m2)

tensor([[4., 5.],
        [5., 6.]])


> 브로드캐스팅은 편리하지만, 자동으로 실행되는 기능이므로 사용자 입장에서 굉장히 주의해서 사용  

> 만약, 두 텐서의 크기가 다르다고 에러를 발생시킨다면 사용자는 이 연산이 잘못되었음을 바로 알 수 있지만 브로드캐스팅은 자동으로 수행되므로 사용자는 나중에 원하는 결과가 나오지 않았더라도 어디서 문제가 발생했는지 찾기가 굉장히 어려울 수 있음.

### 4) 자주 사용되는 기능들

- **행렬 곱셈과 곱셈의 차이(Matrix Multiplication Vs. Multiplication)**

In [13]:
# 행렬 곱셈
m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])
print('Shape of Matrix 1: ', m1.shape) # 2 x 2
print('Shape of Matrix 2: ', m2.shape) # 2 x 1
print(m1.matmul(m2)) # 2 x 1

Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
tensor([[ 5.],
        [11.]])


In [14]:
# 원소별 곱셈
m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]]) # [[1], [2]] -> [[1, 1], [2, 2]]
print('Shape of Matrix 1: ', m1.shape) # 2 x 2
print('Shape of Matrix 2: ', m2.shape) # 2 x 1
print(m1 * m2) # 2 x 2
# print(m1.mul(m2))

Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
tensor([[1., 2.],
        [6., 8.]])


- **평균(Mean)**

In [15]:
# 1차원
t = torch.FloatTensor([1, 2])
print(t.mean())

tensor(1.5000)


In [16]:
# 2차원
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t.mean())
# 차원을 인자로 주는 경우(해당 차원을 제거한다는 의미)
print(t.mean(dim=0)) # 행의 차원 제거
print(t.mean(dim=1)) # 열의 차원 제거
print(t.mean(dim=-1)) # 마지막 차원 제거

tensor(2.5000)
tensor([2., 3.])
tensor([1.5000, 3.5000])
tensor([1.5000, 3.5000])


- **덧셈(Sum)**

In [17]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t.sum()) # 단순히 원소 전체의 덧셈을 수행
print(t.sum(dim=0)) # 행을 제거
print(t.sum(dim=1)) # 열을 제거
print(t.sum(dim=-1)) # 열을 제거

tensor(10.)
tensor([4., 6.])
tensor([3., 7.])
tensor([3., 7.])


- **최대(Max)와 아그맥스(ArgMax)**

In [18]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t.max()) # Returns one value: max
print(t.max(dim=0)) # Returns two values: max and argmax

tensor(4.)
torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))


> max에 dim 인자를 주면 argmax도 함께 리턴

In [19]:
# max 또는 argmax만 리턴받고 싶다면
print('Max: ', t.max(dim=0)[0])
print('Argmax: ', t.max(dim=0)[1])

Max:  tensor([3., 4.])
Argmax:  tensor([1, 1])


- **뷰(View)** - 원소의 수를 유지하면서 텐서의 크기 변경

In [20]:
# PyTorch 텐서의 뷰(View)는 Numpy에서의 리쉐이프(Reshape)와 같은 역할
t = np.array([[[0, 1, 2],
               [3, 4, 5]],
              [[6, 7, 8],
               [9, 10, 11]]])
ft = torch.FloatTensor(t)
print(ft.shape)

print("\n<3차원 텐서에서 2차원 텐서로 변경>")
print(ft.view([-1, 3])) # ft라는 텐서를 (?, 3)의 크기로 변경
print(ft.view([-1, 3]).shape)

print("\n<3차원 텐서의 크기 변경>")
print(ft.view([-1, 1, 3]))
print(ft.view([-1, 1, 3]).shape)

torch.Size([2, 2, 3])

<3차원 텐서에서 2차원 텐서로 변경>
tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])

<3차원 텐서의 크기 변경>
tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])
torch.Size([4, 1, 3])


- **스퀴즈(Squeeze)** - 1인 차원을 제거

In [21]:
ft = torch.FloatTensor([[0], [1], [2]])
print(ft)
print(ft.shape)

print("\n<두번째 차원이 1이므로 squeeze를 사용>")
print(ft.squeeze())
print(ft.squeeze().shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])

<두번째 차원이 1이므로 squeeze를 사용>
tensor([0., 1., 2.])
torch.Size([3])


- **언스퀴즈(Unsqueeze)** - 특정 위치에 1인 차원을 추가

In [22]:
ft = torch.Tensor([0, 1, 2])
print(ft.shape)

print("\n<첫번째 차원에 1인 차원을 추가>")
print(ft.unsqueeze(0)) # 인덱스가 0부터 시작하므로 0은 첫번째 차원을 의미한다.
print(ft.unsqueeze(0).shape)
# == print(ft.view(1, -1))

torch.Size([3])

<첫번째 차원에 1인 차원을 추가>
tensor([[0., 1., 2.]])
torch.Size([1, 3])


- **타입 캐스팅(Type Casting)**
  
![Type Casting](./data/Type_Casting.JPG)

> 텐서에는 자료형이라는 것이 있음.  
> 각 데이터형별로 정의되어져 있는데, 예를 들어 32비트의 유동 소수점은 torch.FloatTensor를, 64비트의 부호 있는 정수는 torch.LongTensor를 사용.  
> GPU 연산을 위한 자료형도 있음 (ex. torch.cuda.FloatTensor)

>> 이 자료형을 변환하는 것을 타입 캐스팅이라고 함.

In [23]:
# long 타입의 lt라는 텐서를 선언
lt = torch.LongTensor([1, 2, 3, 4])
print(lt)
print(lt.float()) # 텐서에다가 .float()를 붙이면 바로 float형으로 타입이 변경

tensor([1, 2, 3, 4])
tensor([1., 2., 3., 4.])


In [24]:
# Byte 타입의 bt라는 텐서를 선언
bt = torch.ByteTensor([True, False, False, True])
print(bt)
print(bt.long()) # .long()이라고하면 long 타입의 텐서로 변경
print(bt.float()) # .float()이라고 하면 float 타입의 텐서로 변경

tensor([1, 0, 0, 1], dtype=torch.uint8)
tensor([1, 0, 0, 1])
tensor([1., 0., 0., 1.])


- **연결하기(concatenate)**

In [25]:
x = torch.FloatTensor([[1, 2], [3, 4]])
y = torch.FloatTensor([[5, 6], [7, 8]])
# 어느 차원을 늘릴 것인지를 인자로 줄 수 있음.
print(torch.cat([x, y], dim=0)) # (2 X 2) -> (4 X 2)
print(torch.cat([x, y], dim=1)) # (2 X 2) -> (2 X 4)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])
tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])


- **스택킹(Stacking)**

In [26]:
x = torch.FloatTensor([1, 4])
y = torch.FloatTensor([2, 5])
z = torch.FloatTensor([3, 6])
print(torch.stack([x, y, z]))
# == print(torch.cat([x.unsqueeze(0), y.unsqueeze(0), z.unsqueeze(0)], dim=0))
print(torch.stack([x, y, z], dim=1)) # 두번째 차원이 증가

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])
tensor([[1., 2., 3.],
        [4., 5., 6.]])


- **ones_like와 zeros_like** - 0으로 채워진 텐서와 1로 채워진 텐서

In [27]:
x = torch.FloatTensor([[0, 1, 2], [2, 1, 0]])
print(x)
print(torch.ones_like(x)) # 입력 텐서와 크기를 동일하게 하면서 값을 1로 채우기
print(torch.zeros_like(x)) # 입력 텐서와 크기를 동일하게 하면서 값을 0으로 채우기

tensor([[0., 1., 2.],
        [2., 1., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


- **In-place Operation** - 덮어쓰기 연산

In [28]:
x = torch.FloatTensor([[1, 2], [3, 4]])
print(x.mul(2.)) # 곱하기 2를 수행한 결과를 출력
print(x) # 기존의 값 출력

print("\n<'_'를 붙이면 기존의 값을 덮어씀>")
print(x.mul_(2.))  # 곱하기 2를 수행한 결과를 변수 x에 값을 저장하면서 결과를 출력
print(x) # 기존의 값 출력

tensor([[2., 4.],
        [6., 8.]])
tensor([[1., 2.],
        [3., 4.]])

<'_'를 붙이면 기존의 값을 덮어씀>
tensor([[2., 4.],
        [6., 8.]])
tensor([[2., 4.],
        [6., 8.]])
